# -*- coding: utf-8 -*-
"""LR5_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQl3AN2n6BBqj4kW9VBs3CrgYoNb1fS6
"""

import streamlit as st
import torch
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image
import pandas as pd
import torch.nn.functional as F

# ---------------------------------------------------
# Step 1: Configure Streamlit page
# ---------------------------------------------------
st.set_page_config(
    page_title="CPU Image Classification (ResNet18)",
    layout="centered"
)

st.title("CPU-Based Image Classification using ResNet18")
st.write("This application classifies images using a pre-trained ResNet18 model.")

# ---------------------------------------------------
# Step 2 & 3: Import libraries and configure CPU only
# ---------------------------------------------------
device = torch.device("cpu")

# ---------------------------------------------------
# Step 4: Load pre-trained ResNet18 model
# ---------------------------------------------------
weights = models.ResNet18_Weights.DEFAULT
model = models.resnet18(weights=weights)
model.eval()
model.to(device)

# Load ImageNet class labels
class_names = weights.meta["categories"]

# ---------------------------------------------------
# Step 5: Image preprocessing (ResNet18 recommended)
# ---------------------------------------------------
preprocess = weights.transforms()

# ---------------------------------------------------
# Step 6: User interface for image upload
# ---------------------------------------------------
uploaded_file = st.file_uploader(
    "Upload an image (JPG or PNG)",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    # Display uploaded image
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_container_width=True)

    # ---------------------------------------------------
    # Step 7: Convert image to tensor and run inference
    # ---------------------------------------------------
    input_tensor = preprocess(image).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)

    # ---------------------------------------------------
    # Step 8: Softmax + Top-5 predictions
    # ---------------------------------------------------
    probabilities = F.softmax(output[0], dim=0)
    top5_prob, top5_idx = torch.topk(probabilities, 5)

    top5_classes = [class_names[idx] for idx in top5_idx]

    # Create results table
    results_df = pd.DataFrame({
        "Class": top5_classes,
        "Probability": top5_prob.numpy()
    })

    st.subheader("Top-5 Predictions")
    st.dataframe(results_df)

    # ---------------------------------------------------
    # Step 9: Bar chart visualization
    # ---------------------------------------------------
    st.subheader("Prediction Probability Distribution")
    st.bar_chart(
        results_df.set_index("Class")
    )

# ---------------------------------------------------
# Footer
# ---------------------------------------------------
st.markdown("---")
st.caption("Model: ResNet18 (Pre-trained on ImageNet) | CPU-only inference")